### ISSUE TITLE
[ros2topic] nested calls to convert_value results in inconsistent printing format

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2cli#129]
## Bug report

originally reported at https://github.com/ros2/ros2cli/pull/126#issuecomment-409378728, and investigated by @yechun1 at https://github.com/ros2/ros2cli/pull/126#issuecomment-409434386.

#### Steps to reproduce issue

Shell 1:
```
ros2 run image_tools cam2image -b
```
Shell 2:
```
$ ros2 topic echo /image sensor_msgs/Image -l 2
```

#### Expected behavior

Print the following to console
```
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: '12'
height: 240
width: 320
encoding: bg...
is_bigendian: 0
step: 960
data: [0, 0, '...']
```
#### Actual behavior

The last element is printed with 5 dots
```
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: '12'
height: 240
width: 320
encoding: bg...
is_bigendian: 0
step: 960
data: [0, 0, '.....']
```

#### Additional information
From https://github.com/ros2/ros2cli/pull/126#issuecomment-409434386:

root caused the issue related with previous code which inside nested _convert_value function. 

 Execute:  "ros2 topic echo /topic -l 2"

with test code, first time convert data to  (first if, for t in (bytes, list, str, tuple))
```
value [0, 0, '...']
k in value [0, 0, '...']
k: 0
k: 0
k: ...
```
second time call nested convert_value by (second elfi, for t in (list, tuple))
when k=...
len(k) = 3, truncate_length = 2.
convert the '...' as real data as '..' and append another '...'
so the result is "....."

while "ros2 topic echo /topic -l 3" is correct 
when k='...'
 if (len("...") > truncate_length) is not ture. skip convert.

Is it possible to remove nested function for _convert_value, it's a little difficult to understand.
