### ISSUE TITLE
ros2 topic can only echo certian topics on multiplemachine setup

### ISSUE THREAD

**Issue by zhaxiche** [ros2/ros2cli#412]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Debian packages
- Version or commit hash:
  - Dashing
- DDS implementation:
  - Default
- Client library (if applicable):
  - rclpy, sensor_msgs

#### Steps to reproduce issue

Machine 1 and machine 2 are connected in the same internet with cables.
On machine 1 (a TX2 board connecting to an intel realsense camera)
```
ros2 run realsense_ros2_camera realsense_ros2_camera

```
On machine 2 (just a Ubuntu PC)
```ros2 topic echo /camera/color/image_raw```

#### Expected behavior
```header:
  stamp:
    sec: 1575322766
    nanosec: 739626472
  frame_id: camera_color_optical_frame
height: 480
width: 640
encoding: rgb8
is_bigendian: 0
step: 1920
data: [178, 164, 150, 180, 166, 153, 182, 168, 157, 183, 169, 158, 177, 167, 159, 171, 161, 153, 174, 159, 155, 178, 162, 158, 183, 169, 162, 183, 169, 162, 180, 164, 152, 180, 164, 152, 184, 166, 152, 190, 172, 158, 189, 176, 160, 188, 175, 159, 189, 176, 160, 183, 170, 154, 176, 158, 142, 173, 155, 138, 177, 156, 143, 185, 164, 151, 183, 169, 158, 183, 169, 158, 181, 166, 160, 186, 171, 165, 186, 176, 170, 188, 178, 172, 185, 175, 167, 181, 171, 163, 181, 167, 154, 178, 164, 150, 183, 166, 158, 191, 174, 166, 191, 179, 170, 189, 177, 167, 189, 177, 167, 189, 177, 167, 188, 181, 170, 184, 177, 166, 181, 175, 168, 177, 171, 164, 181, 173, '...']
---
```
#### Actual behavior
sometimes showing nothing, sometimes showing `Could not determine the type for the passed topic
`
#### Additional information

----
However, I can run `ros2 topic echo /camera/color/camera_info` on machine 2 and it will show
```
header:
  stamp:
    sec: 1575322993
    nanosec: 970160222
  frame_id: camera_color_optical_frame
height: 480
width: 640
distortion_model: plumb_bob
d: [0.0, 0.0, 0.0, 0.0, 0.0]
k: [607.7052001953125, 0.0, 316.7220153808594, 0.0, 607.013427734375, 245.95919799804688, 0.0, 0.0, 1.0]
r: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
p: [607.7052001953125, 0.0, 316.7220153808594, 0.0, 0.0, 607.013427734375, 245.95919799804688, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: false
---
```
I did't do anythinig about DDS and RTPS, I just use the default one. I also have other sensors onboard on machine 1 and after testing many topics, I feel like any topics that involve huge data transmitting will be blocked like an Image/Camera topic.

Any thought on this?

Thanks,

Tom
