### ISSUE TITLE
return raw parameter content without type information

### ISSUE THREAD

**Issue by christian-rauch** [ros2/ros2cli#820]
#### Feature description

`ros2 param get` needs an option to return the raw content of a parameter. Currently, it prepends the parameter content with the value type.

For example:
```sh
ros2 param get /move_group robot_description
```
returns:
```
String value is: <?xml version="1.0" ?> [...] <robot name="panda"> [...] </robot>
```

It would be much more useful if `get` would return the raw content of the parameter, i.e. the URDF string in the case above without `String value is: ` prepended, such that it can be parsed by another tool.

#### Implementation considerations
This can be implemented by a new flag for `get`, that either adds or omits the type information (`String value is: `). IMHO, it makes more sense to omit the type by default and only add type information when the "verbose type" flag is set.

**Comment by fujitatomoya** [comment]
@christian-rauch thanks for creating issue.

are you specifically requesting the format with xml? i do not think xml is not supported even with `load` or `dump`.

> It would be much more useful if get would return the raw content of the parameter, i.e. the URDF string in the case above without String value is:  prepended, such that it can be parsed by another tool.

can you share the actual use case if you have with examples?

btw, you can `dump` the parameters in yaml file.

```yaml
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param dump /parameter_blackboard
/parameter_blackboard:
  ros__parameters:
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
```
