### ISSUE TITLE
ros2 topic hz perform worse than c++ code, also worse than result in another docker container

### ISSUE THREAD

**Issue by Chenxintang** [ros2/ros2cli#843]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu18.04
- Installation type:
  - source
- Version or commit hash:
  - humble
- DDS implementation:
  - FastDDS

#### Steps to reproduce issue

- run two docker container using the following docker-compose.yml
```yaml
container1:
    image: image_name
    network_mode: "host"
    cpuset: 2-9
    cpu_shares: 2048
    shm_size: 4G
    container_name: container1
    runtime: nvidia
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
```
```yaml
container2:
    image: image_name
    network_mode: "host"
    privileged: true
    cpuset: 12-17
    cpu_shares: 2048
    shm_size: 2G
    container_name: container2
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
```
- publish `sensor_msgs::msg::PointCloud2` type message with frequency 10hz in container1
- run subscriber and process data c++ code in container2, record the frequency subscription callback called
- use `ros2 topic hz` tool follow the frequency of topic in both containers
#### Expected behavior
- In both containers, `ros2 topic hz` shows the same frequency which is around 10hz
- Log of c++ code in container2 shows that pointcloud2 messages arrive each 100ms 
#### Actual behavior
- In container1 terminal, `ros2 topic hz` shows frequency slightly under 10hz
![ros2 topic hz result in container1](https://github.com/ros2/ros2cli/assets/75031872/b8f54c40-38fe-4369-9776-73c7804406da)
- In container2 terminal, `ros2 topic hz` shows frequency highly under 10hz, verity from 7hz to 9hz
![ros2 topic hz result in container2](https://github.com/ros2/ros2cli/assets/75031872/1821d199-0aec-4c77-a576-7467bba9562c)
- In log of container2, c++ code receive message each 100ms stably
![c++ code log of container2](https://github.com/ros2/ros2cli/assets/75031872/b4711c88-5ed7-43e6-8d55-971b8d9a2ab6)

#### Additional information
Since code in both container are quite complicate, I can't paste the code here.
As discussed in the blow question, ros2 topic hz result is lower than c++ code because the qos used is different. But why the hz results in different containers turn out to be different?
>https://answers.ros.org/question/350753/ros2-topic-hz-provides-wrong-rate-for-larger-msgs/
Also, since ros2 topic hz result is not reliable, is therea a better way to track the transportaion stability between many nodes?
