### ISSUE TITLE
Allow ros2 topic echo output to be used in ros2 topic pub

### ISSUE THREAD

**Issue by Ryanf55** [ros2/ros2cli#919]
#### Feature description

I want to use `ros2 topic echo`, copy the contents of a message in CLI, and run `ros2 topic pub` to publish the data without having to reformat it. 

Currently, you can echo a topic like this:
```
$ ros2 topic echo /geo_path --once
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: ''
poses:
- header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: ''
  pose:
    position:
      latitude: 1.0
      longitude: 2.0
      altitude: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
- header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: ''
  pose:
    position:
      latitude: 4.0
      longitude: 5.0
      altitude: 6.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
---
```

Then, you need to tediously reformat it like this to publish:
```bash
$ ros2 topic pub /geo_path geographic_msgs/msg/GeoPath '{poses: [{pose: {position: {latitude: 1.0, longitude: 2.0, altitude: 3.0}}}, {pose: {position: {latitude: 4.0, longitude: 5.0, altitude: 6.0}}}]}'
```

#### Implementation considerations

Proposal: Allow publishing by yaml file like so:
`ros2 topic pub /geo_path geographic_msgs/msg/GeoPath --yaml my_message.yaml`

Where `my_message.yaml` is the direct YAML from ros2 topic echo.

I'm open to other alternatives such as `cat` operation on the yaml file and piping it to `xargs`. 
`cat my_message.yaml | xargs  -I{} ros2 topic pub /geo_path geographic_msgs/msg/GeoPath {}`

**Comment by clalancette** [comment]
Does the `--flow-style` parameter to `ros2 topic echo` do what you want?

**Comment by Ryanf55** [comment]
Yea, looks like it does. 
```
ros2 topic echo /geo_path --flow-style
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: ''
poses: [{header: {stamp: {sec: 0, nanosec: 0}, frame_id: ''}, pose: {position: {latitude: 1.0, longitude: 2.0, altitude: 3.0}, orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}}}, {header: {stamp: {sec: 0, nanosec: 0}, frame_id: ''}, pose: {position: {latitude: 4.0, longitude: 5.0, altitude: 6.0}, orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}}}]
---
```

Then, copy the content, type the command, add quotes for the message, and paste it in. 

```

ros2 topic pub /geo_path geographic_msgs/msg/GeoPath "header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: ''
poses: [{header: {stamp: {sec: 0, nanosec: 0}, frame_id: ''}, pose: {position: {latitude: 1.0, longitude: 2.0, altitude: 3.0}, orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}}}, {header: {stamp: {sec: 0, nanosec: 0}, frame_id: ''}, pose: {position: {latitude: 4.0, longitude: 5.0, altitude: 6.0}, orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}}}]"
```

If this is the intent of `flow-style`, perhaps the docs could make that clearer?
